/* Datos de ejemplo: el contenido de "Seguimiento RDR Global 2026" del
   28/09/2026 (la presentación a partir de la que se construyó la plantilla).
   Sirve de semilla del panel y del script scripts/seguimiento-ejemplos.mjs. */

let seq = 0;
const T = (fase, nombre, fecha, asignacion, avance, estado, comentarios = [], extra = {}) => ({
  id: `t${++seq}`,
  fase,
  nombre,
  fecha,
  asignacion,
  avance,
  estado,
  comentarios,
  ...extra,
});

export const EJEMPLO = {
  fechaReunion: "2026-09-28",
  proyectos: [
    {
      id: "p1",
      nombre: "Decomisado MIDAS · Migración Operaciones",
      nombreCorto: "Migración MIDAS",
      sdatool: "SDATOOL-51125",
      traspaso: "2025-51",
      interno: "Lucía Garrido",
      responsable: "Marta",
      tareas: [
        T("pruebas", "Soporte pruebas", "Q3", "Marta", 95, "en_plazo",
          ["Soporte pruebas UAT", "Soporte pruebas DataX"], { inicio: "2026-06-29" }),
        T("pruebas", "Soporte pre simulacro", "2026-07-31", "Marta", 100, "en_plazo",
          ["Carga y publicación DDFF Simulacro Técnico"]),
        T("pruebas", "Simulacro técnico", "2026-08-03", "Marta", 100, "en_plazo", ["Soporte a simulacro"]),
        T("pruebas", "Soporte pre simulacro usuario", "2026-08-28", "Marta", 100, "en_plazo",
          ["Carga y publicación DDFF Simulacro Usuario"]),
        T("pruebas", "Simulacro usuario", "2026-08-29", "Marta", 100, "en_plazo", ["Soporte a simulacro"]),
        T("implantacion", "Implantación a producción", "Q4", "Marta", 0, "sin_iniciar",
          ["Nuevos métodos de liquidación", "DataX - SICOR"]),
      ],
    },
    {
      id: "p2",
      nombre: "Decomisado MIDAS · Cargador Thirdparties",
      sdatool: "SDATOOL-51125",
      traspaso: "2026-21",
      interno: "Lucía Garrido",
      responsable: "Marta",
      tareas: [
        T("analisis", "", "2026-07-02", "Marta", 100, "en_plazo", ["Alcance funcional"], { inicio: "2026-06-29" }),
        T("desarrollo", "", "2026-08-07", "Marta", 90, "en_riesgo", [
          "El propietario de la hoja no puede ser una persona nominativa, sino un grupo",
          "Sinergia entre usuarios trabajando al mismo tiempo, o que no borren la info",
          "El usuario que no tenga permisos de edición sobre el app script",
          "Google Sheet no puede ser repositorio de código",
        ]),
        T("pruebas", "Pruebas unitarias", "2026-08-14", "Marta", 90, "en_curso", ["Pruebas unitarias"]),
        T("pruebas", "Pruebas de usuario", "2026-08-20", "Marta", 100, "en_plazo", ["Pruebas usuario"]),
        T("implantacion", "", "Q4", "Marta", 0, "sin_iniciar", ["Implantación en producción"]),
      ],
    },
    {
      id: "p3",
      nombre: "Decomisado MIDAS · Agreements CLS BBVA México",
      nombreCorto: "Agreements CLS",
      sdatool: "SDATOOL-51125",
      traspaso: "2026-49",
      interno: "Lucía Garrido",
      responsable: "Marta",
      tareas: [
        T("analisis", "", "Q2", "Marta", 100, "en_plazo", ["Alcance funcional"]),
        T("desarrollo", "", "Q2", "Marta", 100, "en_plazo", [
          "Adaptación ventana para añadir tipología CLS",
          "Adaptación servicio online",
          "Adaptación extracción genérica",
        ]),
        T("pruebas", "Pruebas unitarias", "Q2", "Marta", 100, "en_plazo", ["Pruebas unitarias"]),
        T("desarrollo", "", "2026-07-07", "Marta", 100, "en_plazo", ["Bug LAGRDuplis"], { inicio: "2026-06-29" }),
        T("pruebas", "Pruebas integradas", "2026-08-03", "Marta", 100, "en_plazo", ["Pruebas integradas"]),
        T("pruebas", "Pruebas de usuario", "2026-08-14", "Marta", 100, "en_plazo", ["Pruebas usuario"]),
        T("implantacion", "", "2026-09-26", "Marta", 100, "en_plazo", ["Implantación en producción"],
          { inicio: "2026-09-14" }),
      ],
    },
    {
      id: "p4",
      nombre: "Security Lending Undisclosed · Validaciones",
      nombreCorto: "Security Lending",
      sdatool: "SDATOOL-38779",
      traspaso: "2026-52",
      interno: "Lucía Garrido",
      responsable: "Pablo",
      tareas: [
        T("analisis", "", "2026-08-07", "Pablo", 100, "en_plazo", ["Alcance funcional"], { inicio: "2026-07-20" }),
        T("desarrollo", "", "2026-08-31", "Pablo", 100, "en_plazo", [
          "Modificación búsqueda operativa de contrapartidas desde local y global",
          "Validaciones CalypsoId Multientity Legal Agreements",
          "Regularización de casos productivos",
        ]),
        T("pruebas", "", "2026-10-01", "Pablo", 99, "en_plazo",
          ["Pruebas unitarias", "Pruebas integradas", "Pruebas de usuario"]),
        T("implantacion", "", "2026-10-17", "Marta", 0, "sin_iniciar", ["Implantación en producción"]),
      ],
    },
    {
      id: "p5",
      nombre: "BSI 2.0",
      sdatool: "SDATOOL-49629",
      traspaso: "2026-50",
      interno: "Alejandro García",
      responsable: "Pablo",
      tareas: [
        T("analisis", "", "Q3", "Marta", null, "en_plazo", ["Análisis de impacto. Cambio Enterprise BSI"],
          { inicio: "2026-06-29" }),
        T("pruebas", "Soporte a pruebas", "Q3", "Marta", null, "en_plazo",
          ["Soporte a pruebas con Calypso KRFN, KLYO, Murex e Impact"]),
        T("implantacion", "Ventana Legal Agreements BSI", "2026-10-17", "Pablo", 0, "sin_iniciar",
          ["Implantación de la ventana"], { inicio: "2026-10-12" }),
      ],
    },
    {
      id: "p6",
      nombre: "Automatización Emisiones RV",
      sdatool: "SDATOOL-42226",
      traspaso: "2026-46",
      interno: "Alejandro García",
      responsable: "Pablo",
      tareas: [
        T("analisis", "", "2026-04-17", "Pablo", 100, "en_plazo", ["Alcance funcional"]),
        T("desarrollo", "", "2026-06-12", "Pablo", 100, "en_plazo", [
          "Añadir campos de alta de emisores en la ventana de emisiones + botón que llame al proceso",
          "Crear nuevo workflow que llame al alta de emisores y al alta rol emisor",
          "Nuevo proceso que añada el rol emisor a emisores descargados",
          "Publicación de País de Mercado en servicios de Securities (online y batch)",
        ]),
        T("pruebas", "Pruebas unitarias", "2026-07-10", "Pablo", 100, "en_plazo", ["Pruebas unitarias del proceso"]),
        T("pruebas", "Pruebas de usuario", "2026-07-15", "Pablo", 100, "en_plazo", ["Pruebas de usuario"]),
        T("implantacion", "", "2026-07-25", "Pablo", 100, "en_plazo", ["Implantación de componentes"]),
        T("soporte", "", "Q3", "Pablo", null, "en_plazo",
          ["Soporte a pruebas de otros aplicativos: 4sight, Asset Control…"]),
      ],
    },
    {
      id: "p7",
      nombre: "Calypso OTC Madrid Fase V",
      nombreCorto: "OTC V",
      sdatool: "SDATOOL-34546",
      traspaso: "2025",
      interno: "Alejandro Romero",
      responsable: "Marta",
      tareas: [
        T("analisis", "Análisis DDFF post simulacro", "Q2", "Marta", 100, "en_plazo", ["Revisión DDFF post simulacro 18/04"]),
        T("desarrollo", "", "Q2", "Marta", 100, "en_plazo", ["Parametrización nuevos métodos de liquidación"]),
        T("pruebas", "Simulacro · Carga SDIs, SCIs y Notis", "2026-07-10", "Marta", 100, "en_plazo",
          ["Carga y publicación DDFF Simulacro"], { inicio: "2026-06-29" }),
        T("implantacion", "GoLive · Carga SDIs, SCIs y Notis", "2026-07-13", "Marta", 100, "en_plazo",
          ["Carga y publicación DDFF GoLive"]),
        T("post", "Soporte", "Q3", "Marta", 100, "en_plazo", ["Soporte post Go Live"]),
        T("pruebas", "Simulacro", "2026-09-12", "Marta", 100, "en_plazo", ["Soporte simulacro fin de semana"],
          { inicio: "2026-09-11" }),
      ],
    },
    {
      id: "p8",
      nombre: "Eventos Corporativos",
      sdatool: "SDATOOL-51827",
      traspaso: "2026-41",
      interno: "Pablo Rodríguez",
      responsable: "Pablo",
      tareas: [
        T("analisis", "", "Q2", "Pablo", 100, "en_plazo", ["Revisión modificaciones Q1", "Alcance funcional"]),
        T("desarrollo", "", "Q2", "Pablo", 100, "en_plazo", [
          "Completar ventana Eventos Corporativos. Alta y modificación",
          "Canonización Eventos Corporativos",
          "Ventana auditoría modificación / alta campos",
          "Creación entrada assembly para colas",
          "Query de publicación online, masiva y dirigida",
          "Recepción ACK / NACK",
          "Aperiódico creación de campos. Valores desplegables",
        ]),
        T("pruebas", "Pruebas unitarias", "2026-08-31", "Pablo", 100, "en_plazo", ["Pruebas unitarias"],
          { inicio: "2026-06-29" }),
        T("pruebas", "Pruebas integradas", "2026-08-31", "Pablo", 100, "en_plazo", ["Pruebas integradas con SIVA/MUV"]),
        T("pruebas", "Pruebas de usuario", "2026-08-31", "Pablo", 100, "en_plazo", ["Pruebas de usuario"]),
        T("implantacion", "", "2026-10-03", "Pablo", 0, "sin_iniciar", ["Implantación de los componentes"],
          { inicio: "2026-09-28" }),
      ],
    },
    {
      id: "p9",
      nombre: "Testing / IA - RDR",
      sdatool: "",
      traspaso: "BAU · 2026",
      interno: "Juan Manuel Fernández Tudero",
      responsable: "Pablo",
      tareas: [
        T("testing", "Testing", "Q3", "Pablo", 80, "en_plazo", [
          "Documentación de procesos RDR",
          "Clasificación de procesos RDR",
          "Modularización de procesos RDR",
          "Definición de herramienta de ejecuciones: AtSQA",
          "Definición de prerrequisitos en cada proceso",
          "Definición de casos de prueba por cada proceso",
          "Estructura de datos sintéticos",
        ], { inicio: "2026-08-03" }),
      ],
    },
    {
      id: "p10",
      nombre: "Vulnerabilidades Java",
      nombreCorto: "Vulnerabilidades",
      sdatool: "SDATOOL-51827",
      traspaso: "2026-54",
      interno: "José María Parra",
      responsable: "Chema",
      tareas: [
        T("analisis", "", "2026-07-27", "Chema", 100, "en_plazo", [
          "Análisis Javas InHouse (batch): creación de bloques",
          "Análisis infraestructura (EARs, JBOSS, Workbench)",
        ], { inicio: "2026-06-29" }),
        T("desarrollo", "", "2026-08-17", "Chema", 100, "en_plazo", [
          "Generación de pruebas unitarias: Javas InHouse",
          "Mavenización",
          "Adaptación Java InHouse (batch): JDK 17",
          "Mitigación de vulnerabilidades",
          "Generación de los casos de test de cobertura: Javas InHouse",
        ], { sufijo: "B1" }),
        T("desarrollo", "", "2026-09-07", "Chema", 80, "en_plazo", [], { sufijo: "B2" }),
        T("desarrollo", "", "2026-10-19", "Chema", 20, "sin_iniciar", [], { sufijo: "B3" }),
        T("pruebas", "", "2026-08-24", "Chema", 100, "en_plazo",
          ["Pruebas unitarias (Java 17): Javas InHouse", "Test de cobertura"], { sufijo: "Unitarias · B1" }),
        T("pruebas", "", "2026-09-14", "Chema", 65, "en_plazo", [], { sufijo: "Unitarias · B2" }),
        T("pruebas", "", "2026-10-19", "Chema", 10, "sin_iniciar", [], { sufijo: "Unitarias · B3" }),
        T("implantacion", "", "2026-09-26", "Chema", 0, "en_riesgo", ["Implantación"], { sufijo: "B1" }),
        T("implantacion", "", "2026-10-03", "Chema", 0, "en_riesgo", [], { sufijo: "B2" }),
        T("implantacion", "", "2026-11-07", "Chema", 0, "sin_iniciar", [], { sufijo: "B3" }),
      ],
    },
    {
      id: "p11",
      nombre: "Institucional Clientes · E-Clients",
      sdatool: "SDATOOL-34546",
      traspaso: "2026-39",
      interno: "Alejandro Romero",
      responsable: "Marta",
      anexo: true,
      tareas: [
        T("analisis", "", "2026-02-06", "Pilar", 100, "en_plazo", ["Planificación", "Alcance funcional"]),
        T("desarrollo", "", "2026-02-13", "Pilar", 100, "en_plazo",
          ["Inclusión de los alias en el Servicio de Inactivaciones"]),
        T("pruebas", "Pruebas unitarias", "2026-03-13", "Pilar", 100, "en_plazo", ["Pruebas unitarias"]),
        T("pruebas", "Pruebas integradas", "2026-03-27", "Marta", 100, "en_plazo", ["Pruebas integradas con E-Clients"]),
        T("implantacion", "", "2026-07-11", "Marta", 100, "en_plazo", ["Implantación en producción"]),
      ],
    },
  ],
  incidencias: [
    {
      id: "i1",
      tipo: "incidencia",
      estado: "en_riesgo",
      titulo: "Strategic Boost",
      detalle: [
        "Duplicados en ISSR, en el alta automática de emisores",
        "Error en el proceso si el usuario deja vacío el Legal Regime",
      ],
      icono: "warning",
    },
    {
      id: "i2",
      tipo: "tarea",
      estado: "en_riesgo",
      titulo: "2024-57",
      detalle: ["Eliminar columnas no utilizadas FT_T_RLA1"],
      icono: "database",
    },
    {
      id: "i3",
      tipo: "tarea",
      estado: "en_plazo",
      titulo: "Migración Midas FX",
      detalle: ["Volcado de BBDD"],
      icono: "transfer",
    },
  ],
  traspasos: [
    { id: "tr1", codigo: "2025-61", proyecto: "Supply Chain Finance - Contrapartidas",
      interno: "Alejandro Romero", nfq: "Ángela Montero", pendiente: "Falta OK usuario", tipo: "ok_usuario" },
    { id: "tr2", codigo: "2026-21", proyecto: "Cargador Thirdparties",
      interno: "Lucía Garrido", nfq: "Marta Trujillano", pendiente: "Falta implantación GoLive", tipo: "implantacion" },
    { id: "tr3", codigo: "2026-23", proyecto: "Cargador Fondos",
      interno: "Lucía Garrido", nfq: "Jesús Tejada", pendiente: "Falta OK usuario", tipo: "ok_usuario" },
    { id: "tr4", codigo: "2026-49", proyecto: "Legal Agreements CLS",
      interno: "Lucía Garrido", nfq: "Marta Trujillano", pendiente: "Falta OK usuario / OK destino", tipo: "ok_usuario" },
  ],
};
